In [2]:
from pathlib import Path
import tensorflow as tf
import sys

# appending llm_components path to sys.path to easily import
sys.path.append('/kaggle/input/datasets/harshit1234g/axiomlm-utils')
import llm_components as lc

In [3]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

## Paths

In [4]:
# directories
utils_dir = Path('/kaggle/input/datasets/harshit1234g/axiomlm-utils')
data_dir = utils_dir / 'wikitext_npy'

# dataset paths
train_path = data_dir / 'train.npy'
valid_path = data_dir / 'valid.npy'
test_path = data_dir / 'test.npy'

# tokenizer
tokenizer_path =  str(utils_dir / 'sp_tokenizer.model')

# Path for checkpoint directory, the reason for 2 checkpoint directories is because 
# kaggle reads from input directory, but saves in working directory
checkpoint_restore_dir = utils_dir / 'checkpoints'
checkpoint_save_dir = Path('/kaggle/working/checkpoints')

## Hyper Parameters

In [5]:
SEQUENCE_LEN = 512      # Context size
SHIFT = SEQUENCE_LEN    # using shift = seq_len because the dataset is quite large
BATCH_SIZE = 64         # previously used 128 batch size, but got OOM
N_EMBEDS = 512          # or d_model
N_HEADS = 8
N_BLOCKS = 8
STEPS_PER_EPOCH = 3000

In [6]:
target_tokens = 800_000_000
token_per_step = BATCH_SIZE * SEQUENCE_LEN
token_per_chunk = STEPS_PER_EPOCH * token_per_step
total_steps = round(target_tokens // token_per_step, -3)
warmup_steps = int(total_steps * 0.05)  # 5%
print(f'Total target tokens: {target_tokens:3,}')
print(f'Steps per epoch: {STEPS_PER_EPOCH:3,}')
print(f'Token per step: {token_per_step:3,}')
print(f'Token per chunk/epoch: {token_per_chunk:3,}')
print(f'Total steps for cosine decay: {total_steps:3,}')
print(f'Warmup steps for cosine decay: {warmup_steps:3,}')

Total target tokens: 800,000,000
Steps per epoch: 3,000
Token per step: 32,768
Token per chunk/epoch: 98,304,000
Total steps for cosine decay: 24,000
Warmup steps for cosine decay: 1,200


## Loading Data

In [7]:
default_params = {
    'seq_len': SEQUENCE_LEN,
    'batch_size': BATCH_SIZE,
    'shift': SHIFT,
    'shuffle_buffer': 10_000
}
train_ds = lc.create_dataset_from_npy(
    npy_path= train_path, 
    training= True,
    **default_params
)
valid_ds = lc.create_dataset_from_npy(
    npy_path= valid_path, 
    training= False,
    **default_params
)
test_ds = lc.create_dataset_from_npy(
    npy_path= test_path, 
    training= False,
    **default_params
)

I0000 00:00:1771924944.153104      55 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13757 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1771924944.159323      55 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13757 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5


In [8]:
for item in train_ds.take(1):
    print(item)

(<tf.Tensor: shape=(64, 512), dtype=int32, numpy=
array([[  701, 14217,   267, ...,  7599,   738,   267],
       [ 8995,   285,  4690, ..., 15974,   275,  2361],
       [ 6237,  1820,  5317, ...,   428,   928,  3232],
       ...,
       [  270,   267,   355, ...,   286, 10816,  4895],
       [ 1290,  1193,   582, ...,   317, 15945,   317],
       [ 1084,   262, 10670, ...,   376,   264,   475]], dtype=int32)>, <tf.Tensor: shape=(64, 512), dtype=int32, numpy=
array([[14217,   267,   386, ...,   738,   267,   307],
       [  285,  4690,   275, ...,   275,  2361,   264],
       [ 1820,  5317,  5793, ...,   928,  3232,  8805],
       ...,
       [  267,   355, 12192, ..., 10816,  4895,   287],
       [ 1193,   582,   264, ..., 15945,   317,   317],
       [  262, 10670,  2949, ...,   264,   475,  2381]], dtype=int32)>)


## Callbacks, Strategy, Vocab size & pad id

In [8]:
tensorboard_cb = tf.keras.callbacks.TensorBoard(
    log_dir= 'logs',
    histogram_freq= 1,
    update_freq= 100,    # every 100 batch
    embeddings_freq= 1
)

In [9]:
strategy = tf.distribute.MirroredStrategy()

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')


In [10]:
sp = lc.load_sp_tokenizer(str(tokenizer_path))
vocab_size = sp.get_piece_size()
pad_id = sp.pad_id()
vocab_size, pad_id

(16000, 3)

## Transformer Model

In [11]:
with strategy.scope():
    # creating model
    model = lc.GPT(
        vocab_size= vocab_size,
        seq_len= SEQUENCE_LEN,
        n_embeds= N_EMBEDS,
        n_heads= N_HEADS,
        n_blocks= N_BLOCKS
    )

    # lr schedule
    lr_schedule = lc.WarmupCosine(
        base_lr= 5e-4,
        warmup_steps= warmup_steps,
        total_steps= total_steps
    )

    # optimizer
    optimizer = tf.keras.optimizers.AdamW(
        learning_rate= lr_schedule,
        weight_decay= 0.005,
        beta_2= 0.98,
        clipnorm= 1.0
    )

    # softmax is handled by loss function
    loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits= True)

    # compiling
    model.compile(
        optimizer= optimizer,
        loss= loss_fn,
        metrics= [lc.Perplexity(pad_id= pad_id)]
    )

    # passing dummy input to build model
    dummy = tf.zeros((1, SEQUENCE_LEN), dtype= tf.int32)
    _ = model(dummy, training= False)

    # checkpoint logic
    checkpoint = tf.train.Checkpoint(
        model= model,
        optimizer= optimizer
    )

    latest_ch = tf.train.latest_checkpoint(checkpoint_restore_dir)
    if latest_ch:
        print('Restoring State from', latest_ch)
        
        optimizer.build(model.trainable_variables)
        checkpoint.restore(latest_ch).assert_existing_objects_matched()
        
        print('Step:', optimizer.iterations.numpy())
        print('LR:', lr_schedule(optimizer.iterations).numpy())
        print('Optimizer Variables:', len(optimizer.variables))    # must be larger than 100

    else:
        print('No Checkpoint found, random initialization.')

    manager = tf.train.CheckpointManager(
        checkpoint,
        checkpoint_save_dir,
        max_to_keep= 3
    )

Restoring State from /kaggle/input/datasets/harshit1234g/axiomlm-utils/checkpoints/ckpt-1
Step: 3000
LR: 0.00049311505
Optimizer Variables: 185


In [12]:
model.summary()

Model: "gpt"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (1, 512, 512)          │     8,192,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_1 (Embedding)         │ (512, 512)             │       262,144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_block               │ ?                      │     3,150,848 │
│ (TransformerBlock)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_block_1             │ ?                      │     3,150,848 │
│ (TransformerBlock)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_block_2             │ ?                      │     3,150,848 │
│ (TransformerBlock)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_block_3             │ ?                      │     3,150,848 │
│ (TransformerBlock)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_block_4             │ ?                      │     3,150,848 │
│ (TransformerBlock)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_block_5             │ ?                      │     3,150,848 │
│ (TransformerBlock)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_block_6             │ ?                      │     3,150,848 │
│ (TransformerBlock)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ transformer_block_7             │ ?                      │     3,150,848 │
│ (TransformerBlock)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer_normalization_16          │ ?                      │         1,024 │
│ (LayerNormalization)            │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,985,857 (385.23 MB)

 Trainable params: 33,661,952 (128.41 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 67,323,905 (256.82 MB)

In [13]:
history = model.fit(
    train_ds, 
    steps_per_epoch= STEPS_PER_EPOCH,
    epochs= 1,
    validation_data= valid_ds,
    callbacks= [tensorboard_cb]
)

INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Redu

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/epoch_iterator.py:160: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()


3000/3000 ━━━━━━━━━━━━━━━━━━━━ 6311s 2s/step - loss: 3.7324 - ppl: 41.8669 - val_loss: 3.4285 - val_ppl: 30.8308


In [14]:
test_loss, test_perplexity = model.evaluate(test_ds)
print(f'{test_loss = }\n{test_perplexity = }')

8/8 ━━━━━━━━━━━━━━━━━━━━ 6s 761ms/step - loss: 3.3845 - ppl: 29.6359
test_loss = 3.415231227874756
test_perplexity = 30.423982620239258


In [15]:
manager.save()

'/kaggle/working/checkpoints/ckpt-2'

In [17]:
model.save('AxiomLM-33M-Base.keras')

In [16]:
import subprocess

# creating zip of kaggle working directory to easily download it on my system
subprocess.run(['zip', '-r', 'working_dir.zip', '/kaggle/working'], stdout= subprocess.DEVNULL)

CompletedProcess(args=['zip', '-r', 'working_dir.zip', '/kaggle/working'], returncode=0)